---
title             : "Annalise's R Notebook for d2m/psychopathy"
shorttitle        : "d2m/psychopathy"

author: 
  - name          : "Annalise Halverson"
    affiliation   : "1"
    corresponding : yes    # Define only one corresponding author
    address       : "Postal address"
    email         : "my@email.com"
    role: # Contributorship roles (e.g., CRediT, https://credit.niso.org/)
      - "Conceptualization"
      - "Writing - Original Draft Preparation"
      - "Writing - Review & Editing"
  - name          : "Ernst-August Doelle"
    affiliation   : "1,2"
    role:
      - "Writing - Review & Editing"
      - "Supervision"

affiliation:
  - id            : "1"
    institution   : "Wilhelm-Wundt-University"
  - id            : "2"
    institution   : "Konstanz Business School"

authornote: |
  Add complete departmental affiliations for each author here. Each new line herein must be indented, like this line.

  Enter author note here.

abstract: |
  One or two sentences providing a **basic introduction** to the field,  comprehensible to a scientist in any discipline.
  Two to three sentences of **more detailed background**, comprehensible  to scientists in related disciplines.
  One sentence clearly stating the **general problem** being addressed by  this particular study.
  One sentence summarizing the main result (with the words "**here we show**" or their equivalent).
  Two or three sentences explaining what the **main result** reveals in direct comparison to what was thought to be the case previously, or how the  main result adds to previous knowledge.
  One or two sentences to put the results into a more **general context**.
  Two or three sentences to provide a **broader perspective**, readily comprehensible to a scientist in any discipline.
  
  <!-- https://tinyurl.com/ybremelq -->
  
keywords          : "keywords"
wordcount         : "X"

bibliography      : "r-references.bib"

floatsintext      : no
linenumbers       : yes
draft             : no
mask              : no

figurelist        : no
tablelist         : no
footnotelist      : no

classoption       : "man"
output            : papaja::apa6_pdf
---

```{r setup, include = FALSE}
library("papaja")
r_refs("r-references.bib")
getwd()
setwd("../Tests/")
source("assignment 2.R")
```

```{r analysis-preferences}
# Seed for random number generation
set.seed(42)
knitr::opts_chunk$set(cache.extra = knitr::rand_seed)
```

```{r callhello_worldfunction}
getwd()
setwd("../Code/")
source("defining-functions.R")
call("hello_world")
```


# Methods
We report how we determined our sample size, all data exclusions (if any), all manipulations, and all measures in the study. <!-- 21-word solution (Simmons, Nelson & Simonsohn, 2012; retrieved from http://ssrn.com/abstract=2160588) -->

## Participants

## Material

## Procedure

## Data analysis
We used `r cite_r("r-references.bib")` for all our analyses.

```{r PAI_BOR_data_readin}

getwd()
setwd("../localonly/") # I don't know if I should be doing this every time but it's the only way I've figured out how to set path

messy_PAI_BOR_df1 <- read_xlsx("Decety_assessment_data_copy.xlsx", sheet = "PAI_BOR", range = cell_cols("A")) # grab ID column
messy_PAI_BOR_df2 <- read_xlsx("Decety_assessment_data_copy.xlsx", sheet = "PAI_BOR", range = cell_cols("Z")) # grab PAI total score column
messy_PAI_BOR_df <- cbind(messy_PAI_BOR_df1, messy_PAI_BOR_df2) # combine 2 columns into one dataframe displaying unique ID and PAI BOR total score

print(messy_PAI_BOR_df)

# my data here is tidy since i only copied over columns i needed. however, this is a very simplified version of all the data i will be using. i purposefully picked an 'easy' sheet to practice with.
# the original sheet had score ticks for each question. for my purposes, this information was unnecessary.
  
```

```{r create_PAI_BOR_intermediate_dataset}

# 2 dplyr functions for pai-bor
# filter out non -1001 data points
PAIBOR_Total_Score <- ("PAIBOR_Total_Score")
filtered_messy_PAI_BOR_df <- messy_PAI_BOR_df %>% filter(PAIBOR_Total_Score > 0)
print(filtered_messy_PAI_BOR_df)

# arrange lowest to highest
sorted_filtered_messy_PAI_BOR_df <- filtered_messy_PAI_BOR_df %>% arrange(PAIBOR_Total_Score)
print(sorted_filtered_messy_PAI_BOR_df)

write.csv(sorted_filtered_messy_PAI_BOR_df, "cleanish_PAIBOR_sorted_filtered.csv", row.names = FALSE)
# not sure if I should keep lowest to highest as that ruins the order for the other sheets. it was a good test

```

# Results

# Discussion

# Header A
* **bananas**
* *carrots*
* eggs

## Header B
1. France
2. Spain
3. **_Australia_**

### Header C
[R class website](https://nrdowling.github.io/d2m/index.html)
<!-- reference this page whenever you have questions -->

\newpage

# References

::: {#refs custom-style="Bibliography"}
:::
